In [1]:
import tensorflow as tf
tf.__version__

'2.10.0'

In [2]:
mnist = tf.keras.datasets.mnist  ### VERİ YÜKLEME ###
(x_train,y_train),(x_test,y_test) = mnist.load_data() ## Veri setini yükledik

In [3]:
### VERİ ÖN İŞLEME ###
x_train, x_test = x_train/255.0, x_test/255.0

In [4]:
x_train.shape

(60000, 28, 28)

In [5]:
x_test.shape

(10000, 28, 28)

In [6]:
### MODEL KURMA ###
model= tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'), #nöron sayısı belirledik
    tf.keras.layers.Dropout(0.2), #overfittingi çözmek için düzleştirme yaptık
    tf.keras.layers.Dense(10) #kategori sayısı 10dur
])

In [7]:
predictions = model(x_train[:1]).numpy()
predictions #ilk eğitim verisini alıp ekrana yazdırdık

array([[ 0.12993239, -0.6057707 , -0.06336705, -0.23128161,  0.20214556,
        -0.28751338,  0.48243847, -0.00662355,  0.38016325, -0.6811406 ]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.1141874 , 0.054715  , 0.09411727, 0.07956919, 0.12273826,
        0.07521835, 0.16244623, 0.09961224, 0.14665338, 0.05074271]],
      dtype=float32)

In [9]:
y_true =[1,2]
y_pred = [[0.05,0.95,0],[0.1,0.8,0.1]]
scce = tf.keras.losses.SparseCategoricalCrossentropy()   #Kayıp hesaplaması yaptık
scce(y_true,y_pred).numpy()

1.1769392

In [10]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)

In [11]:
loss_fn(y_train[:1],predictions).numpy() #Eğitim değil gerçek verilere göre hata değerimiz

2.58736

In [12]:
###Ağırlık Güncelleme ###
model.compile(optimizer="adam",
              loss=loss_fn,
              metrics=["accuracy"])


In [13]:
model.fit(x_train,y_train,epochs=5) ##model eğitimi

Epoch 1/5
1875/1875 [==============================] - 10s 4ms/step - loss: 0.2973 - accuracy: 0.9147
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1454 - accuracy: 0.9573
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1095 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0881 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0754 - accuracy: 0.9758


In [14]:
model.evaluate(x_test,y_test,verbose=2) #test verisi ile ölçüm

313/313 - 1s - loss: 0.0727 - accuracy: 0.9769 - 1s/epoch - 4ms/step


[0.07270429283380508, 0.9768999814987183]

In [15]:
##Yeni Veri Tahmini ##
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [16]:
predictions=probability_model.predict(x_test[:1])
predictions

1/1 [==============================] - 0s 126ms/step


array([[1.8453207e-08, 1.3205992e-07, 4.0831892e-05, 4.5345930e-04,
        5.3946066e-11, 2.6219834e-05, 3.8978096e-10, 9.9947709e-01,
        1.6924258e-07, 2.1409280e-06]], dtype=float32)

In [17]:
import numpy as np
np.argmax(predictions[0])

7

In [18]:
y_test[:1][0] ##model resmin etiketini doğru tahmin etti.

7